export const browserCoreExamples = [
  "openhearth browser status",
  "openhearth browser start",
  "openhearth browser stop",
  "openhearth browser tabs",
  "openhearth browser open https://example.com",
  "openhearth browser focus abcd1234",
  "openhearth browser close abcd1234",
  "openhearth browser screenshot",
  "openhearth browser screenshot --full-page",
  "openhearth browser screenshot --ref 12",
  "openhearth browser snapshot",
  "openhearth browser snapshot --format aria --limit 200",
  "openhearth browser snapshot --efficient",
  "openhearth browser snapshot --labels",
];

export const browserActionExamples = [
  "openhearth browser navigate https://example.com",
  "openhearth browser resize 1280 720",
  "openhearth browser click 12 --double",
  'openhearth browser type 23 "hello" --submit',
  "openhearth browser press Enter",
  "openhearth browser hover 44",
  "openhearth browser drag 10 11",
  "openhearth browser select 9 OptionA OptionB",
  "openhearth browser upload /tmp/openhearth/uploads/file.pdf",
  'openhearth browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openhearth browser dialog --accept",
  'openhearth browser wait --text "Done"',
  "openhearth browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openhearth browser console --level error",
  "openhearth browser pdf",
];
